name: terraform apply
on:
  push:
    tags: ["v*"]          # git tag v0.1.0 -> deploy

permissions:
  contents: read
  id-token: write         # needed for OIDC -> STS

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production           # ← move it here
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region:     ${{ vars.AWS_REGION }}

      - name: Clean .terraform cache
        run: |
          cd envs/prod
          rm -rf .terraform

      - name: Terraform Init
        run: |
          cd envs/prod
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="dynamodb_table=${{ vars.TF_STATE_TABLE }}"

      - name: Terraform Apply
        run: |
          cd envs/prod
          terraform apply -auto-approve
