name: terraform plan
on:
  push:
    branches:
      - main
permissions: { contents: read, id-token: write }

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region:     ${{ vars.AWS_REGION }}
      - run: cd envs/prod && terraform init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" -backend-config="dynamodb_table=${{ vars.TF_STATE_TABLE }}"
      - run: cd envs/prod && terraform plan -no-color
